name: Generate Snake

permissions:
  contents: write   # Allow push

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ashutoshiru
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output   # Branch where SVG will be pushed
          publish_dir: dist       # Correct param name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

